# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: aster

builds:
  - main: .
    binary: aster
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

homebrew_casks:
  - name: aster
    commit_author:
      name: mobanhawi
      email: mobanhawi@users.noreply.github.com
    homepage: https://github.com/mobanhawi/aster
    description: Terminal disk usage analyzer for macOS
    license: MIT
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr",
              args: ["-dr", "com.apple.quarantine", "#{staged_path}/aster"]
          end
    repository:
      owner: mobanhawi
      name: homebrew-aster
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"